global:
  scrape_interval: 5s

scrape_configs:
- job_name: 'docker'
  static_configs:
  - targets:
    - 'host.docker.internal:9323'

- job_name: 'cadvisor'
  static_configs:
  - targets:
    - 'cadvisor:8080'

- job_name: 'loki'
  static_configs:
  - targets:
    - 'loki:3100'

- job_name: 'alertmanager'
  static_configs:
  - targets:
    - 'alertmanager:9093'

- job_name: 'prometheus'
  static_configs:
  - targets:
    - 'prometheus:9090'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
